#!/usr/bin/env python3
"""Generate CRD field references and validate the downloadable documentation examples."""
import argparse
import json
from pathlib import Path

import yaml
from jsonschema import Draft4Validator

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "docs/site"
NOTES = {
    "TsugaPostgresMonitoring": "Monitor one PostgreSQL server through a dedicated collector forwarding to the cluster agent. Requires TsugaCollectorConfig named `cluster`. Use one resource per server: the database role `otel_monitor` is shared. Include `provisioning` explicitly; managed mode requires an admin Secret, while manual mode requires DBA setup. Resource names are limited to 43 characters. See the [DBM guide](../kubernetes-monitoring/dbm.md).",
    "SLO": "Manage a native Tsuga SLO with an event- or time-based SLI. Targets must be strictly between 0 and 100; windows are 7, 30, or 90 days. SLI and alert configurations are passed through to Tsuga for validation. Omitting clusterIds selects all clusters; omitting alerts removes alerts. Remote updates recreate alerts with new IDs. See the [SLO guide](../slos/index.md).",
    "Dashboard": "Widget IDs (`spec.graphs[].id`) are required by the Kubernetes schema. Visualization objects pass through to the Tsuga API; Kubernetes does not validate their internal contract.",
    "Monitor": "Use `dashboardRef: {name: example-dashboard}` for a Dashboard in the same namespace. If both fields are supplied, `dashboardId` takes precedence. Configuration objects pass through to the Tsuga API.",
    "TsugaCollectorConfig": "The name must be `cluster` (enforced by the CRD), so at most one config exists: TsugaMonitoring looks up that exact name, and collector child names are fixed. Secrets must exist in `collectorNamespace`. At least one agent signal must remain enabled. See [runtime defaults](configuration.md) for collector images and resources, which are resolved in code rather than by the CRD.",
    "TsugaMonitoring": "Use one resource per namespace to avoid competing workload annotation owners. With `injectExistingWorkloads: false`, annotate selected pod templates manually; there is no implemented opt-in label selector.",
}


def cell(value):
    return str(value).replace("|", "&#124;").replace("\n", " ")


def fields(schema, prefix=""):
    for name, prop in schema.get("properties", {}).items():
        path = f"{prefix}.{name}" if prefix else name
        constraints = []
        for key in ("enum", "minimum", "maximum", "minLength", "maxLength", "minItems", "maxItems", "exclusiveMinimum", "exclusiveMaximum", "pattern"):
            if key in prop:
                constraints.append(f"{key}: `{cell(json.dumps(prop[key]))}`")
        if "enum" in prop.get("items", {}):
            constraints.append(f'item enum: `{cell(json.dumps(prop["items"]["enum"]))}`')
        if prop.get("x-kubernetes-preserve-unknown-fields"):
            constraints.append("Opaque JSON; validated by Tsuga")
        description = prop.get("description", "—")
        # These comments describe intent, not the current controller behavior.
        if path == "spec.image":
            description = "Override the image for agent, gateway, and scraper; see runtime defaults."
        required = "Yes" if name in schema.get("required", []) else "No"
        default = f'`{cell(json.dumps(prop["default"]))}`' if "default" in prop else "—"
        kind = prop.get("type", "JSON")
        if kind == "array":
            kind += f' of {prop.get("items", {}).get("type", "JSON")}'
        yield f"| `{path}` | {kind} | {required} | {default} | {cell(description)} {'; '.join(constraints)} |"
        yield from fields(prop, path)
        if "items" in prop:
            yield from fields(prop["items"], path + "[]")
        for rule in prop.get("x-kubernetes-validations", []):
            yield f'| `{path}` validation | CEL | — | — | {cell(rule.get("message", rule["rule"]))} |'


def render(crd, version):
    spec = crd["spec"]
    kind = spec["names"]["kind"]
    schema = version["schema"]["openAPIV3Schema"]
    return "\n".join([
        "---", "# Generated by hack/docs.py. Edit schemas or the generator, then regenerate.",
        "hide:", "  - toc", "---", f"# {kind}", "",
        f'**API:** `{spec["group"]}/{version["name"]}` · **Scope:** {spec["scope"]} · **Short name:** `{spec["names"]["shortNames"][0]}`', "",
        NOTES[kind], "", "## Fields", "",
        "Required is relative to the containing object. Defaults inside optional objects apply only when the containing object exists. Status is read-only. Standard Kubernetes metadata fields are omitted.", "",
        "| Field | Type | Required | Schema default | Description and constraints |",
        "| --- | --- | --- | --- | --- |",
        *fields({"properties": {k: v for k, v in schema["properties"].items() if k in ("spec", "status")}, "required": schema.get("required", [])}), "",
        *[line for rule in schema.get("x-kubernetes-validations", []) for line in ("Validation: " + cell(rule.get("message", rule["rule"])), "")],
        "## Source", "",
        f'[CRD schema](https://github.com/tsuga-dev/tsuga-operator/blob/main/config/crd/bases/{spec["group"]}_{spec["names"]["plural"]}.yaml).', "",
        "This table is generated from the checked-in schema. See [configuration and compatibility](configuration.md) for runtime behavior and [example manifests](../examples/index.md) for complete resources.", "",
    ])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated pages are stale")
    args = parser.parse_args()
    schemas = {}
    failures = []
    for path in sorted((ROOT / "config/crd/bases").glob("*.yaml")):
        crd = yaml.safe_load(path.read_text())
        for version in crd["spec"]["versions"]:
            if not version["served"]:
                continue
            kind = crd["spec"]["names"]["kind"]
            schemas[(crd["spec"]["group"] + "/" + version["name"], kind)] = version["schema"]["openAPIV3Schema"]
            target = SITE / "reference" / f"{kind.lower()}.md"
            content = render(crd, version)
            if args.check:
                if not target.exists() or target.read_text() != content:
                    failures.append(f"Stale reference: {target.relative_to(ROOT)}; run make docs-reference")
            else:
                target.write_text(content)
    examples = sorted((SITE / "examples").glob("*.yaml"))
    for path in examples:
        for obj in yaml.safe_load_all(path.read_text()):
            if obj is None:
                continue
            if not isinstance(obj, dict) or not isinstance(obj.get("spec"), dict) or not isinstance(obj.get("metadata"), dict):
                failures.append(f"{path.name}: expected a Kubernetes object with metadata and spec mappings")
                continue
            schema = schemas.get((obj.get("apiVersion"), obj.get("kind")))
            if schema is None:
                failures.append(f'{path.name}: no served CRD schema for apiVersion {obj.get("apiVersion")!r}, kind {obj.get("kind")!r}')
                continue
            # OpenAPI v3 CRDs use boolean exclusive bounds, as in JSON Schema draft 4.
            for error in Draft4Validator(schema).iter_errors(obj):
                failures.append(f'{path.name}: {list(error.path)}: {error.message}')
            # JSON Schema does not evaluate Kubernetes CEL rules.
            if obj["kind"] == "TsugaPostgresMonitoring":
                provisioning = obj["spec"].get("provisioning")
                if provisioning is None or (provisioning.get("mode", "managed") == "managed" and not provisioning.get("adminSecretRef", {}).get("name")):
                    failures.append(f"{path.name}: managed provisioning requires adminSecretRef.name; use explicit manual mode otherwise")
                if len(obj["metadata"].get("name", "")) > 43:
                    failures.append(f"{path.name}: PostgreSQL resource names must be at most 43 characters")
            if obj["kind"] == "TsugaCollectorConfig":
                prom = obj["spec"].get("prometheus", {})
                if prom.get("replicas", 1) > 1 and not prom.get("targetAllocator", {}).get("enabled", False):
                    failures.append(f"{path.name}: multiple scraper replicas require a Target Allocator")
    if failures:
        raise SystemExit("\n".join(failures))
    print(f"Checked {len(schemas)} CRD references and {len(examples)} example files.")


if __name__ == "__main__":
    main()
